### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by Maaike0904** [Maaike0904/connect-your-tribe-squad-page#6]
Voorbeeld die we kunnen gebruiken: <link rel="shortcut icon" type="assets/png" href="assets/Favicon_homerun.png">

**Comment by Maaike0904** [comment]
<link rel="shortcut icon" type="assets/png" href="assets/Favicon_homerun.png">
<img width="269" alt="Scherm­afbeelding 2023-02-22 om 13 03 39" src="https://user-images.githubusercontent.com/112861144/220614823-2e7174c7-3b14-45df-a7da-60f57c70aa9a.png">

**Comment by Maaike0904** [comment]
<link rel="icon" type="image/x-icon" href="/images/favicon.ico">

**Comment by Nazneen05x** [comment]
Done!
